### ISSUE TITLE
Error when running github action

### ISSUE THREAD

**Issue by jderochervlk** [chrysanthos/simple-asset-size-reporter#2]
I am seeing the following error:

```
 Run chrysanthos/simple-asset-size-reporter@1.0.0
2s
    build-assets: false
Run chrysanthos/simple-asset-size-reporter@1.0.0
  with:
    repo-token: ***
    files: ["dist/.js"]
    with-same: false
    build-assets: false
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
/usr/bin/git checkout 60ed245099341642e9714b70b9c0e054f619acdd
Previous HEAD position was 80f95fbc Merge 463a7e29c72a18616f39ead8afe118435775b76c into 60ed245099341642e9714b70b9c0e054f619acdd
HEAD is now at 60ed2450 feat(git actions): add bundle watch (#7)
Could not create a comment automatically.
##[error]body is not defined
```

I'm not sure how to troubleshoot this.  Any help is appreciated.

**Comment by chrysanthos** [comment]
It seems like the action is unable to add a comment on the PR. Did you provide the `repo-token`? Can you show me your .yml file?

**Comment by jderochervlk** [comment]
```
name: Simple Asset Size Reporter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - uses: chrysanthos/simple-asset-size-reporter@1.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        files: '["dist/.js"]'
        with-same: 'false'
        build-assets: 'false'
```
